### ISSUE TITLE
How can I use the Dialog?

### ISSUE THREAD

**Issue by won5572** [hydrostack/hydro-sales#1]
I saw the dialog code, but I'm not sure exactly how to use it.

**Comment by kjeske** [comment]
Hi!

First you need to create your dialog component:

`SimpleDialog.cshtml`
```razor
@model SimpleDialog

<dialog class="modal modal-open">
  <div class="modal-box">
    <h3 class="font-bold text-lg">Hello!</h3>
    <p class="py-4">
      My dialog
    </p>
    <div class="modal-action">
      <button type="button" class="btn" hydro-on:click="@(() => Model.Close())">
        Close
      </button>
    </div>
  </div>
</dialog>
```

`SimpleDialog.cshtml.cs`
```c#
using Hydro;
using HydroSales.Pages.Shared.Dialogs;

namespace HydroSales.Pages.Customers.AddCustomer;

public class SimpleDialog : HydroComponent, IDialog<SimpleDialogData>
{
    public SimpleDialogData DialogData { get; set; }

    public void Close() =>
        Dispatch(new CloseDialog(nameof(SimpleDialog)), Scope.Global);
}

public record SimpleDialogData();
```

Then you can open it in from another Hydro component:
```c#
public void OpenSimpleDialog() =>
    Dispatch(new OpenDialog(nameof(SimpleDialog), new SimpleDialogData()), Scope.Global);
```

`SimpleDialogData` record is optional and used for passing data to the dialog.

I hope it helped.

**Comment by won5572** [comment]
Thank you for your answer.

I'm wondering that how can I use dialog with layout.
I saw the file in this folder "hydro-sales/Pages/Shared/Dialogs/DialogLayout.cshtml"
I need like "hydro-sales/Pages/Shared/Dialogs/DialogLayout.cshtml"
How can I use this?
How can I pass "Close Event" from layout to HydroComponent.
Is the function of the code below still incomplete?

`<button type="button" class="btn btn-outline-secondary" hydro-handle:click="">@options.CloseLabel</button>`

**Comment by kjeske** [comment]
Dialogs are not used in Sales app, they landed there by accident, and the code for the dialog layout is obsolete and will be removed. You can use instead the code below for dialog's layout. Let's create Hydro View called DialogView:

`DialogView.cshtml`
```razor
@model DialogView

<dialog class="modal modal-open">
  <div class="modal-box">
    <h3 class="font-bold text-lg">
      @Model.Slot("title")
    </h3>
    <p class="py-4">
      @Model.Slot()
    </p>
    <div class="modal-action">
      <button type="button" class="btn" hydro-on:click="@Model.OnClose">
        Close
      </button>
    </div>
  </div>
</dialog>
```

`DialogView.cshtml.cs`
```c#
using System.Linq.Expressions;
using Hydro;

namespace HydroSales.Pages.Customers.AddCustomer;

public class DialogView : HydroView
{
    public Expression<Action> OnClose { get; set; }
}
```

Now you can use it like this in your SimpleDialog:
```razor
@model SimpleDialog

<dialog-view on-close="@(() => Model.Close())">
  <slot name="title">Hello!</slot>
  
  My dialog
</dialog-view>
```

As you can see, your `dialog-view` contains the layout, and you can pass your expression for closing via `on-close` attribute. You can read more about Hydro Views in here:
https://usehydro.dev/utilities/hydro-views.html

**Comment by won5572** [comment]
Thank you for your reply.
I'll try this. It's a good solution.
